version: 2

sources:

    - name: core
      # For bigquery:
      database: de-zoomcamp-10   
      schema: netflix_dataset      
      tables:
        - name: optimized_combined_data_1
        - name: optimized_combined_data_2
        - name: optimized_combined_data_3
        - name: optimized_combined_data_4
        - name: external_movie_titles   


models:
  - name: netflix_movies
    description: >
      Combined movie dataset 
  - name: netflix_movies_final
    description: >
      Dataset used for visualisations

      
  # - name: dm_monthly_zone_revenue
  #   description: >
  #     Aggregated table of all taxi trips corresponding to both service zones (Green and yellow) per pickup zone, month and service.
  #     The table contains monthly sums of the fare elements used to calculate the monthly revenue. 
  #     The table contains also monthly indicators like number of trips, and average trip distance. 
  #   columns:
  #     - name: revenue_monthly_total_amount
  #       description: Monthly sum of the the total_amount of the fare charged for the trip per pickup zone, month and service.
  #       tests:
  #           - not_null:
  #               severity: error
      
      
