# This is a basic workflow to help you get started with Actions
name: Deploy to VM

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths-ignore: # Don't trigger on files that are updated by the CI
      - "README.md"
      - "howto/**"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "autoupdate"
  autoupdate:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: | # multi line script
                  ls
                  cd de-project
                  echo "Fetching the remote branch and moving it to origin/main"
                  git fetch origin main
                  git reset --hard origin/main
                  git status

                  echo "Updating Docker Containers"
                  cd data_pipeline/de_airflow
                  docker-compose down --volumes --rmi all
                  docker-compose build --build-arg ${{ secrets.NAME }} --build-arg ${{ secrets.KEY }}
                  sudo docker-compose up -d
                  echo "We are Up and Running!"

























